### ISSUE TITLE
value was either too large or too small for a uint64

### ISSUE THREAD

**Issue by Edan11** [dessroyed/extcheat#3]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Memory.Mem.Get64BitCode(String name, String path, Int32 size) in C:\projects\memory-dll\Memory\memory.cs:line 603
   at Memory.Mem.GetCode(String name, String path, Int32 size) in C:\projects\memory-dll\Memory\memory.cs:line 361
   at Memory.Mem.ReadByte(String code, String file) in C:\projects\memory-dll\Memory\Methods\Read.cs:line 311
   at MordhauDess.CheatMenu.MeleeTimer_Tick(Object sender, EventArgs e) in C:\Users\Manyu\Desktop\extcheat-master\MordhauDess\CheatMenu.cs:line 52
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MordhauDess
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Manyu/Desktop/extcheat-master/MordhauDess/bin/x64/Release/MordhauDess.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Users/Manyu/Desktop/extcheat-master/MordhauDess/bin/x64/Release/MetroFramework.DLL
----------------------------------------
Memory
    Assembly Version: 1.2.24.0
    Win32 Version: 1.2.24.0
    CodeBase: file:///C:/Users/Manyu/Desktop/extcheat-master/MordhauDess/bin/x64/Release/Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4644.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Users/Manyu/Desktop/extcheat-master/MordhauDess/bin/x64/Release/MetroFramework.Fonts.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by dessroyed** [comment]
at what moment do you have this error?

**Comment by Edan11** [comment]
when open the cheat
the error appear

**Comment by Edan11** [comment]
i play from epic games

**Comment by Edan11** [comment]
![image](https://github.com/dessroyed/extcheat/assets/105978141/e8a0d45f-a231-4db4-9c61-3639db6b27a4)

**Comment by dessroyed** [comment]
I think offsets from epic games is different that from steam

**Comment by dessroyed** [comment]
cheat is for steam version

**Comment by Edan11** [comment]
should i change every offsets for epicgames or just engine and uworld?

**Comment by dessroyed** [comment]
> should i change every offsets for epicgames or just engine and uworld?

idk, maybe only engine and uworld, try it

**Comment by Edan11** [comment]
ok thanks for the answer

**Comment by Edan11** [comment]
are u using cheat engine for search offset ?

**Comment by dessroyed** [comment]
> are u using cheat engine for search offset ?

https://www.unknowncheats.me/forum/unreal-engine-4-a/570218-ue-multitool-class-inspector-sdk-dumper-fn-logger.html
Use this

**Comment by Edan11** [comment]
what injector u use?
when i initialize and try to dump game will crash

**Comment by dessroyed** [comment]
> what injector u use?
> when i initialize and try to dump game will crash

just get offsets from gengine and uworld boxes without dumping, gengine address - game address is offset

**Comment by Edan11** [comment]
Engine : 7ff64b360000 (if i change to this offset , i cant change any value)
World : 7FF650CAEDA0
in boxes just this ? its diffrent from ur source offset

**Comment by dessroyed** [comment]
> Engine : 7ff64b360000 (if i change to this offset , i cant change any value) World : 7FF650CAEDA0 in boxes just this ? its diffrent from ur source offset

Offsets for epic games added in project folder, replace it with usual offsets file
